[package]
name = "mad-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["driver/mmo7"]

[dependencies]
webrender = "0.61.0"
glutin = "0.28.0"
gleam = "0.6.19"
winit = "0.26.1"
png = "0.17.5"
util = { path = "./util" }
