[package]
name = "mad-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["driver/mmo7"]

[dependencies]
webrender = { git = "https://github.com/servo/webrender" }
glutin = "0.28.0"
gleam = "0.13.1"
winit = "0.26.1"
window-vibrancy = "0.1.3"
image = "0.24.2"

util = { path = "./util" }

num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
