[package]
name = "mad-rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[workspace]
members = ["driver/mmo7"]

[dependencies]
slint = "0.2.1"
util = { path = "./util" }

[build-dependencies]
slint-build = "0.2.1"
