import { Button, VerticalBox } from "std-widgets.slint";

export DeviceSelectionWindow := Window {
    property<int> counter: 0;
    callback request-increase-value();
    VerticalBox { 
        Text {
            text: "Counter: \{counter}";
        }
        Button {
            text: "Increase value";
            clicked => { 
                request-increase-value();
            }
        }
     }
}