import "./font/OpenSans.ttf";
import { Button, VerticalBox } from "std-widgets.slint";
import { DeviceSelectionWindow, DeviceData } from "./device_selection.slint";

struct State := {
    name: string
}

export MainWindow := Window {
    property <[State]> app_states: [
        {name: "Device selection"}
    ];
    property <int> app_state: 0;

    // device selection window
    property <[DeviceData]> device_list;

    title: "Mad Rust - " + app_states[app_state].name;
    icon: @image-url("icon-logo.png");
    default-font-family: "OpenSans";
    background: #212121;
    min-height: 300px;
    min-width: 500px;
    no-frame: true;
    preferred-height: 720px;
    preferred-width: 1280px;

    if app_state == 0: Rectangle {
        DeviceSelectionWindow {
            device_list_: device_list;
        }
    }
}